### PR TITLE
Adds the newly added entity domains: `event`, `lawn_mower`, `todo` and `wake_word`

### PR DESCRIPTION
**Pull request by dougiteixeira**
Add the newly added entity domains to the core:
* [event](https://developers.home-assistant.io/docs/core/entity/event/)
* [lawn_mower](https://developers.home-assistant.io/docs/core/entity/lawn-mower/)
* [todo](https://developers.home-assistant.io/docs/core/entity/todo/)
* [wake_word](https://developers.home-assistant.io/docs/core/entity/wake_word/)

### CODE REVIEW

**Comment by joostlek** [comment]
I'll merge this later as I can't update the sheet accordingly right now

**Comment by joostlek** [comment]
Oh shit I forgot about this PR, I'll put it in my to do list for Thursday

**Comment by joostlek** [comment]
Sorry 🙏

**Comment by dougiteixeira** [comment]
No problem, since then there have been several other new entity domains, so it needed to be revised.

**Pull request closed without merging**
